server:
  port: ${APPLICATION_SERVER_PORT}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when-authorized

logging:
  level:
    root: INFO
    org.springframework.boot.devtools.autoconfigure: WARN
    org.hibernate.SQL: WARN
    org.hibernate.orm.jdbc.bind: WARN
spring:
  messages:
    basename: messages/messages
    encoding: UTF-8
  config:
    import:  optional:file:.env[.properties]
  rabbitmq:
    host: ${APPLICATION_RABBIT_MQ_HOST}
    port: ${APPLICATION_RABBIT_MQ_PORT}
    username: ${APPLICATION_RABBIT_MQ_USERNAME}
    password: ${APPLICATION_RABBIT_MQ_PASSWORD}
  mail:
    host: ${APPLICATION_MAIL_HOST}
    port: ${APPLICATION_MAIL_PORT}
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false
  thymeleaf:
    check-template-location: false
  threads:
    virtual:
      enabled: true

  datasource:
    url: jdbc:postgresql://${APPLICATION_DATABASE_HOST}:${APPLICATION_DATABASE_PORT}/${APPLICATION_DATABASE_NAME}
    username: ${APPLICATION_DATABASE_USERNAME}
    password: ${APPLICATION_DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      connection-timeout: 30000
      max-lifetime: 1800000
  jpa:
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.xml

  security:
    oauth2:
      resourceserver:
        jwt:
          jws-algorithms: HS512
  web:
    error:
      whitelabel:
        enabled: false
  servlet:
    multipart:
      max-file-size: ${APPLICATION_STORAGE_MAX_FILE_SIZE}
      max-request-size: ${APPLICATION_STORAGE_MAX_REQUEST_SIZE}

app:
  security:
    secret: ${APPLICATION_SECURITY_SECRET}
    accessTokenLifeTime: ${APPLICATION_SECURITY_ACCESS_TOKEN_LIFE_TIME}
    refreshTokenLifeTime: ${APPLICATION_SECURITY_REFRESH_TOKEN_LIFE_TIME}
    allowedOrigin: ${APPLICATION_SECURITY_ALLOWED_ORIGIN}
  storage:
    allowedMimeTypes: ${APPLICATION_STORAGE_ALLOWED_MIME_TYPES}
    maxFileSize: ${APPLICATION_STORAGE_MAX_FILE_SIZE}
    endpoint: ${APPLICATION_STORAGE_ENDPOINT}
    accessKey: ${APPLICATION_STORAGE_ACCESS_KEY}
    secretKey: ${APPLICATION_STORAGE_SECRET_KEY}
    bucket: ${APPLICATION_STORAGE_BUCKET}
    region: ${APPLICATION_STORAGE_REGION}
  handle:
    reservedHandles: ${APPLICATION_HANDLE_RESERVED_HANDLES}
  mail:
    from: ${APPLICATION_MAIL_FROM}
